### ISSUE TITLE
Volume

### ISSUE THREAD

**Issue by Eldog-02** [craftloop/craftloop-library#2]
Volume indicators, stuff like mute/unmute, a headphone icon and a speaker icon.

Great icons btw, they fit well with soft stuff, rounded corners n such

**Comment by lucaburgio** [comment]
Thank you for your feedback! Some icons were already on the way!
The library has been updated right now and some Audio/Sound/Mute icons are included.

If you have other suggestions just let me know!

**Comment by Eldog-02** [comment]
Wow, that was really fast, thank you! I'll be sure to comment with more suggestions later down the line

**Comment by lucaburgio** [comment]
Great! Thank you for your help!
