### ISSUE TITLE
More social networks icons!

### ISSUE THREAD

**Issue by arielpont** [craftloop/craftloop-library#3]
Hi! I saw that the only icon for social networks on the platform is Instagram. What about Facebook, Twitter, Linkedin, Youtube, Pinterest, Flickr, etc??

**Comment by lucaburgio** [comment]
Hey, i'm planning to release asap other icons, social media included with high priority. I'll update the issue when the icons are live.

**Comment by lucaburgio** [comment]
Twitter, Facebook, Telegram, LinkedIn and Medium have been added. Soon I'll add other socials too, feel free to make a list of them if you want.

**Comment by arielpont** [comment]
Hi Luca! Thank you so much for the work :)

**Comment by lucaburgio** [comment]
You're welcome!
