### ISSUE TITLE
Many icons don't have fill

### ISSUE THREAD

**Issue by evildonuts6** [craftloop/craftloop-library#5]
![image](https://user-images.githubusercontent.com/33640297/44948560-d7910b80-adf5-11e8-97d0-0dfd11492636.png)

**Comment by lucaburgio** [comment]
Please do not re-distribute the project on Icomoon. If you are using Icomoon for your ONLY personal use then is allowed, but re-distribution is not.

**Comment by evildonuts6** [comment]
I am not redistributing, this compilation of icons is for my own personal
usage.

**Comment by lucaburgio** [comment]
Glad to hear this and thank you for your help fixing them!
